// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecnologyStoreApp.Data;

#nullable disable

namespace TecnologyStoreApp.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TecnologyStoreApp.Data.DetallesFactura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadSeleccionada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("colorSeleccionado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("direccionEntrega")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("metodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreProductoSeleccionado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("precioProductoSeleccionado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("totalApagar")
                        .HasColumnType("TEXT");

                    b.HasKey("FacturaId");

                    b.ToTable("DetallesFacturas");
                });
#pragma warning restore 612, 618
        }
    }
}
